name: esavvy.solutions
favicon: null
layout_spectrum: 0.898496723966673
typography_spectrum: 0.9171157423406839
title: eSavvy Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#999999'
    - '#050505'
    - '#0099d5'
    - '#d32d27'
  brandStrength: 0.8172487274277955
  lightness: 0.18838028656318784
  saturation: 0.5314597052056342
  rhythmicContrast: 0.06583011196926236
purpose: []
